id: d7_matomo_user_settings
label: Matomo user settings
migration_tags:
  - Drupal 7
source:
  plugin: d7_user
  constants:
    key: user_account_users
    module: matomo
process:
  uid: uid
  key: 'constants/key'
  module: 'constants/module'
  settings:
    plugin: skip_row_if_not_set
    index: 'custom'
    source: data/matomo
destination:
  plugin: user_data
migration_dependencies:
  required:
    - d7_user
