<?php

/**
 * @file
 * LocalGovDrupal Core module file.
 */

/**
 * Implements hook_theme().
 */
function localgov_core_theme($existing, $type, $theme, $path) {
  return [
    'localgov_page_header_block' => [
      'variables' => [
        'title' => '',
        'lede' => NULL,
      ],
      'render element' => 'block',
    ],
  ];
}

/**
 * Implements hook_template_preprocess_default_variables_alter().
 */
function localgov_core_template_preprocess_default_variables_alter(&$variables) {
  if (theme_get_setting('localgov_base_remove_css')) {
    $variables['localgov_base_remove_css'] = TRUE;
  }
  if (theme_get_setting('localgov_base_remove_js')) {
    $variables['localgov_base_remove_js'] = TRUE;
  }
}
