default:
  image: skpr/php-cli:${PHP_VERSION}-dev-v2-latest
  services:
    - name: mysql:${MYSQL_VERSION}
      alias: mysql

stages:
  - pre
  - build
  - lint
  - test

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_ROOT_PASSWORD: drupal
  MYSQL_DATABASE: drupal
  MYSQL_USER: drupal
  MYSQL_PASSWORD: drupal
  SIMPLETEST_DB: mysql://drupal:drupal@mysql/drupal
  SIMPLETEST_BASE_URL: http://localhost:8080
  BROWSERTEST_OUTPUT_DIRECTORY: app/sites/default/files
  BROWSERTEST_OUTPUT_FILE: test-output.html
  MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"chromeOptions": { "args": [ "--disable-gpu", "--headless" ] } }, "http://chrome:4444/wd/hub" ]'

build app:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - app/vendor/
  script:
    - mkdir -p /tmp/project
    - cp -r ${CI_PROJECT_DIR} /tmp/project/
    - git clone --depth 1 --branch ${DRUPAL_CORE_CONSTRAINT}.x https://git.drupal.org/project/drupal.git app
    - mv /tmp/project app/modules/
    - cd app
    - composer install
    - composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
    - composer config --unset platform.php
    - composer require rlanvin/php-rrule:${RRULE_CONSTRAINT}
    - composer require
      --with-all-dependencies
      dealerdirect/phpcodesniffer-composer-installer
      dpi/drupal-phpunit-bootstrap
      drupal/core-dev:^${DRUPAL_CORE_CONSTRAINT}
      phpspec/prophecy-phpunit:^2
      mglaman/phpstan-drupal:^1
      phpstan/phpstan-deprecation-rules:*
      micheh/phpcs-gitlab
    - composer require
      drupal/coder:^8.3
      drupal/token:^1.5
    - composer show
    - cp modules/project/date_recur/.drupalci/* .
    - mkdir -p ${BROWSERTEST_OUTPUT_DIRECTORY}
  artifacts:
    expire_in: 1 hour
    paths:
      - app/composer.lock
      - app/

phpcs:
  stage: lint
  needs: ["build app"]
  script:
    - cd app
    - vendor/bin/phpcs --standard=modules/project/date_recur/phpcs.xml --report=full --report-\\Micheh\\PhpCodeSniffer\\Report\\Gitlab=phpcs-quality-report.json modules/project/date_recur/
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      codequality: app/phpcs-quality-report.json

phpstan:
  stage: lint
  needs: ["build app"]
  script:
    - cd app
    - vendor/bin/phpstan analyse --memory-limit=2G --no-progress -c phpstan.neon modules/project/date_recur --error-format gitlab > report.json
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      codequality: app/report.json

test unit:
  needs: ["build app"]
  stage: test
  script:
    - cd app
    - vendor/bin/phpunit modules/project/date_recur/tests/src/Unit/ --log-junit report-unit.xml
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/report-unit.xml

test kernel:
  needs: ["build app"]
  stage: test
  before_script:
    - cd app
    - ./wait-for-it.sh -s -t 180 mysql:3306 -- echo "MySQL is Ready"
  script:
    - vendor/bin/phpunit modules/project/date_recur/tests/src/Kernel/ --log-junit report-kernel.xml
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/report-kernel.xml

test functional:
  needs: ["build app"]
  stage: test
  image: skpr/php-cli:${PHP_VERSION}-dev-v2-latest
  services:
    - name: mysql:${MYSQL_VERSION}
      alias: mysql
    - name: selenium/standalone-chrome:3.141.59-oxygen
      alias: chrome
  before_script:
    - cd app
    - php -S 0.0.0.0:8080 .ht.router.php >> http.log 2>&1 &
    - ./wait-for-it.sh -s -t 180 mysql:3306 -- echo "MySQL is Ready"
  script:
    - vendor/bin/phpunit modules/project/date_recur/tests/src/Functional/ --log-junit report-functional.xml
  dependencies:
    - build app
  artifacts:
    when: always
    reports:
      junit: app/report-functional.xml
    paths:
      - app/http.log
      - app/sites/simpletest/browser_output/
