/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, once) {
  Drupal.behaviors.layoutParagraphsBuilderForm = {
    attach: function attach(context) {
      $('.lpb-enable__wrapper').removeClass('hidden');
      $('[data-lpb-form-id]').each(function (i, e) {
        var p = $(e).parents('[data-lpb-id]').toArray().pop();
        var parent = p || e;
        $('.lpb-enable__wrapper', parent).addClass('hidden');
      });
      var events = ['lpb-component:insert.lpb', 'lpb-component:update.lpb', 'lpb-component:move.lpb', 'lpb-component:drop.lpb'].join(' ');
      $(once('lpb-builder-form', '[data-lpb-id]', context)).on(events, function (e) {
        $(e.currentTarget).closest('[data-lpb-form-id]').find('[data-drupal-selector="edit-close"]').val(Drupal.t('Cancel'));
      });
    }
  };
})(jQuery, Drupal, once);