/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  Drupal.behaviors.layoutParagraphsComponentList = {
    attach: function attach(context) {
      $('.lpb-component-list-search-input', context).keyup(function (e) {
        var v = e.currentTarget.value;
        var pattern = new RegExp(v, 'i');
        var $list = $(e.currentTarget).closest('.lpb-component-list').find('.lpb-component-list__item');
        $list.each(function (i, item) {
          if (pattern.test(item.innerText)) {
            item.removeAttribute('style');
          } else {
            item.style.display = 'none';
          }
        });
      });
    }
  };
})(jQuery, Drupal);