# Docker and Docker Compose based environment for Drupal.
# See https://github.com/docksal/docksal for more information and documentation.

# This is a shared configuration file that is intended to be stored in the project repo.
# For local overrides:
# - create .docksal/docksal-local.yml file and put local docker-compose configuration overrides there
# - add .docksal/docksal-local.yml to .gitignore

# Docksal stitches several docker-compose configuration files together.
# Run "fin config" to see which files are involved and the resulting configuration.

version: "3.9"

services:
  # Match platform.sh stack
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: nginx
    depends_on:
      - cli

  redis:
     hostname: redis
     image: redis:6.0-alpine
     volumes:
       - ${PROJECT_ROOT}/.docksal/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
     command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

# If extra/updated software needed in CLI, see .docksal/services/cli/Dockerfile

# Add non-standard services here
  # # MailHog
  # mail:
  #   extends:
  #     file: ${HOME}/.docksal/stacks/services.yml
  #     service: mail

  # Solr
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    image: docksal/solr:8.1-2.1
