<?php

/**
 * @file
 * LocalGovDrupal services landing page module file.
 */

/**
 * Implements hook_theme().
 */
function localgov_services_landing_theme($existing, $type, $theme, $path) {
  return [
    'node__localgov_services_landing__full' => [
      'template' => 'node--localgov-services-landing--full',
      'base hook' => 'node',
    ],
    'taxonomy_vertical_list' => [
      'template' => 'taxonomy-vertical-list',
      'variables' => [
        'title' => '',
        'items' => [],
      ],
    ],
  ];
}
