#!/usr/bin/env bash

## Run BackstopJS
##
## Usage: fin backstop

source ${DOCKSAL_PATH}/.docksal/helpers
ensure_containers_up

check_override $@

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Run backstop
# Trim CR(\r) from the output, otherwise there will be issues passing it to the docker binary on Windows.
# BACKSTOPJS="docker exec $(docker-compose ps -q backstop | tr -d '\r') backstop"
BACKSTOPJS="docker run --rm -v $(pwd):/src backstopjs/backstopjs"
# docker run --rm -v $(pwd):/src backstopjs/backstopjs "$@"
$BACKSTOPJS "$@"
