#!/usr/bin/env bash

## Run 'drush cex' for the project
##
## Usage: fin cex
##

source ${DOCKSAL_PATH}/.docksal/command-settings

ensure_containers_up

cd ${DOCROOT_PATH}
fin drush cex -y
cd ${DOCKSAL_PATH}
git status
