#!/usr/bin/env bash

## Run npm in the theme folder to Compile CSS.
##
## Usage: fin compile-css
##

source ${DOCKSAL_PATH}/.docksal/helpers
ensure_containers_up

check_override $@

cd ${THEME_PATH}

# Install npm
fin npm install
fin exec ./node_modules/.bin/gulp styles
fin cr
