#!/usr/bin/env bash

## Sync files from master folder to local site.
##
## Usage: fin files-download [public|private]
##

source ${DOCKSAL_PATH}/.docksal/command-settings

ensure_containers_up

cd ${DOCROOT_PATH}

# Grab the ssh URL for the project (master environment)
PF_SSH=$($PLATFORM_CMD ssh --pipe -p ${PLATFORM_ID} -e master)

# Public or Private files?
if [[ -z $1 || ! $1 == "public" && ! $1 == 'private' ]]; then
  echo-red "Command failed: You must include whether you want 'public' or 'private', e.g. fin files-download public"
  exit
fi

if [[ $1 == "public" ]]; then
  # Grab public files
  rsync -rvz --exclude 'js' --exclude 'css' --exclude 'php' --exclude 'ctools' --progress --size-only ${PF_SSH}:/app/${DOCROOT}/sites/${SITE_DIRECTORY}/files ${SITEDIR_PATH}
elif [[ $1 == 'private' ]]; then
  # Grab private files
  rsync -rvz --exclude 'js' --exclude 'css' --exclude 'php' --exclude 'ctools' --progress --size-only ${PF_SSH}:/app/private ${PROJECT_ROOT}
fi
