#!/usr/bin/env bash

## Run Code Sniffer (phpcs) against given path
##
## Usage: fin phpcs <path>
##
## Uses Drupal standards.
##
## Includes extensions:	php, module, inc, install, test, profile, theme

source ${DOCKSAL_PATH}/.docksal/helpers
ensure_containers_up

check_override $@

if [[ "$1" == "" ]]; then
	echo "Path argument omitted. Using modules folder."
	path=modules
else
  path=$1
fi

cd $PROJECT_ROOT
fin phpcs \
	--standard=Drupal -n \
	--extensions="php,module,inc,install,test,profile,theme" \
	$path
