#!/usr/bin/env bash

#: exec_target = cli

## Run 'drush sqlq 'TRUNCATE `watchdog`' for the project
## Also clears cache
##
## Usage: fin trunwatch
##

source ${DOCKSAL_PATH}/.docksal/command-settings

ensure_containers_up

cd "${DOCROOT_PATH}" || exit
drush sqlq 'TRUNCATE watchdog;'
drush cr
