# Third party settings for feed type for Feeds Tamper.
feeds.feed_type.*.third_party.feeds_tamper:
  type: mapping
  label: 'Feeds Tamper settings'
  mapping:
    tampers:
      type: sequence
      sequence:
        type: feeds_tamper.[plugin]

# Feeds Tamper instance.
feeds_tamper.*:
  type: tamper.[plugin]
  mapping:
    uuid:
      type: uuid
    plugin:
      type: string
      label: 'Tamper plugin ID'
    source:
      type: string
      label: 'Source field'
    weight:
      type: integer
      label: 'Weight'
    label:
      type: string
      label: 'Label'
    description:
      type: string
      label: 'Description'
