# Schema for the tablefield module display settings.

tablefield.settings:
  type: config_object
  label: 'Tablefield display format settings'
  mapping:
    csv_separator:
      type: string
      label: "separator"
    rows:
      type: integer
      label: "Number of rows"
    cols:
      type: integer
      label: "Number of columns"

field.field_settings.tablefield:
  type: mapping
  label: 'Tablefield field settings'
  mapping:
    export:
      type: boolean
      label: 'Allow users to export table data as CSV'
    restrict_rebuild:
      type: boolean
      label: 'Restrict rebuilding to users with the permission "rebuild tablefield"'
    restrict_import:
      type: boolean
      label: 'Restrict importing to users with the permission "import tablefield"'
    lock_values:
      type: boolean
      label: 'Lock cell default values from further edits during node add/edit. Most commonly used to have fixed values for the header.'
    cell_processing:
      type: integer
      label: 'Table cell processing'
    empty_rules:
      type: mapping
      label: 'Rules for evaluating whether tablefield item should be considered empty'
      mapping:
        ignore_table_structure:
          type: boolean
          label: 'Ignore table structure changes'
        ignore_table_header:
          type: boolean
          label: 'Ignore table header'

field.widget.settings.tablefield:
  type: mapping
  label: 'Tablefield field widget settings'
  mapping:
    input_type:
      type: string
      label: 'Input type'

field.formatter.settings.tablefield:
  type: mapping
  label: 'Tablefield field widget settings'
  mapping:
    row_header:
      type: boolean
      label: 'Display first row as a table header'
    column_header:
      type: boolean
      label: 'Display first column as a table header'
