<?php

/**
 * @file
 * Module file for the localgov_media module.
 */

use Drupal\Core\Config\FileStorage;
use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 */
function localgov_media_modules_installed($modules, $is_syncing) {
  if (!$is_syncing && in_array('localgov_media', $modules)) {

    // Install all optional config now rather than deferring it to later.
    $config_path = \Drupal::service('extension.list.module')->getPath('localgov_media') . '/config/optional';
    $config_source = new FileStorage($config_path);
    \Drupal::service('config.installer')->installOptionalConfig($config_source);

    // Add permission to use the WYSIWYG text format.
    $role_object = Role::load('authenticated');
    $role_object->grantPermission('use text format wysiwyg');
    $role_object->save();
  }
}
