<?php

/**
 * @file
 * Module file for the localgov_media module.
 */

use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 */
function localgov_media_modules_installed($modules, $is_syncing) {
  if (!$is_syncing && in_array('localgov_media', $modules)) {
    // Add permission to use the WYSIWYG text format.
    $role_object = Role::load('authenticated');
    $role_object->grantPermission('use text format wysiwyg');
    $role_object->save();
  }
}
